name = "VP4Optim"
uuid = "8687cf0f-8f6d-4dd6-8e27-64e326ab5325"
authors = ["Carl Ganter <cganter@tum.de>"]
version = "1.0.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "1.0.2"
Compat = "4.16.0"
DocumenterTools = "0.1.20"
LinearAlgebra = "1.11.0"
Optim = "1.10.0"
Plots = "1.40.9"
Random = "1.11.0"
Revise = "3.6.4"
StaticArrays = "1.9.8"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
